"""Private deterministic reference; exclusively uses the public clinic CLI."""
import json
import subprocess
from pathlib import Path

# Generated by qa/build_proto.py from the private rule engine; uploaded only for oracle runs.
ANSWERS = json.loads((Path(__file__).parent / "answers.json").read_text())


def clinic(*args):
    return json.loads(subprocess.check_output(["clinic", *args], text=True))


def solve(answers=None):
    answers = ANSWERS if answers is None else answers
    clinic("patients")
    clinic("history")
    for entry in answers:
        clinic("records", entry["patient"])
    for entry in answers:
        clinic("determine", "--json", json.dumps(entry))
    return clinic("determinations")


if __name__ == "__main__":
    final = solve()
    assert final["complete"] and len(final["determinations"]) == len(ANSWERS)
    print(json.dumps(final, indent=2))
